/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_nativeio_NativeIO */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO
#define _Included_org_apache_hadoop_io_nativeio_NativeIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_initNative
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    getMemlockLimit0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_getMemlockLimit0
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    renameTo0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_renameTo0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    link0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_link0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    copyFileUnbuffered0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_copyFileUnbuffered0
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_CachedUid */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_CachedUid
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_CachedUid
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_Windows */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_Windows
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_Windows
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_GENERIC_READ
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_GENERIC_READ 2147483648i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_GENERIC_WRITE
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_GENERIC_WRITE 1073741824i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_READ
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_READ 1i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_WRITE
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_WRITE 2i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_DELETE
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_SHARE_DELETE 4i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_CREATE_NEW
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_CREATE_NEW 1i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_CREATE_ALWAYS
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_CREATE_ALWAYS 2i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_OPEN_EXISTING
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_OPEN_EXISTING 3i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_OPEN_ALWAYS
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_OPEN_ALWAYS 4i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_TRUNCATE_EXISTING
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_TRUNCATE_EXISTING 5i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_BEGIN
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_BEGIN 0i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_CURRENT
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_CURRENT 1i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_END
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_END 2i64
#undef org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_ATTRIBUTE_NORMAL
#define org_apache_hadoop_io_nativeio_NativeIO_Windows_FILE_ATTRIBUTE_NORMAL 128i64
/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    createDirectoryWithMode0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_createDirectoryWithMode0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    createFile
 * Signature: (Ljava/lang/String;JJJ)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_createFile
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    createFileWithMode0
 * Signature: (Ljava/lang/String;JJJI)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_createFileWithMode0
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    setFilePointer
 * Signature: (Ljava/io/FileDescriptor;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_setFilePointer
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    getOwner
 * Signature: (Ljava/io/FileDescriptor;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_getOwner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    access0
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_access0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_Windows
 * Method:    extendWorkingSetSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024Windows_extendWorkingSetSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_Windows_AccessRight */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_Windows_AccessRight
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_Windows_AccessRight
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_io_nativeio_NativeIO_POSIX_WORKAROUND_NON_THREADSAFE_CALLS_DEFAULT
#define org_apache_hadoop_io_nativeio_NativeIO_POSIX_WORKAROUND_NON_THREADSAFE_CALLS_DEFAULT 1L
#undef org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_READ
#define org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_READ 1L
#undef org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_WRITE
#define org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_WRITE 2L
#undef org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_EXEC
#define org_apache_hadoop_io_nativeio_NativeIO_POSIX_MMAP_PROT_EXEC 4L
/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    getPmdkLibPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_getPmdkLibPath
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    isPmemCheck
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_isPmemCheck
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    pmemMapFile
 * Signature: (Ljava/lang/String;JZ)Lorg/apache/hadoop/io/nativeio/NativeIO/POSIX/PmemMappedRegion;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_pmemMapFile
  (JNIEnv *, jclass, jstring, jlong, jboolean);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    pmemUnMap
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_pmemUnMap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    pmemCopy
 * Signature: ([BJZJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_pmemCopy
  (JNIEnv *, jclass, jbyteArray, jlong, jboolean, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    pmemDrain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_pmemDrain
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    pmemSync
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_pmemSync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    fstat
 * Signature: (Ljava/io/FileDescriptor;)Lorg/apache/hadoop/io/nativeio/NativeIO/POSIX/Stat;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_fstat
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    stat
 * Signature: (Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO/POSIX/Stat;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_stat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    chmodImpl
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_chmodImpl
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    posix_fadvise
 * Signature: (Ljava/io/FileDescriptor;JJI)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_posix_1fadvise
  (JNIEnv *, jclass, jobject, jlong, jlong, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    sync_file_range
 * Signature: (Ljava/io/FileDescriptor;JJI)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_sync_1file_1range
  (JNIEnv *, jclass, jobject, jlong, jlong, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    mlock_native
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_mlock_1native
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    getUIDforFDOwnerforOwner
 * Signature: (Ljava/io/FileDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_getUIDforFDOwnerforOwner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    getUserName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_getUserName__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    getUserName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_getUserName__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    getGroupName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_getGroupName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    mmap
 * Signature: (Ljava/io/FileDescriptor;IZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_mmap
  (JNIEnv *, jclass, jobject, jint, jboolean, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO_POSIX
 * Method:    munmap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_00024POSIX_munmap
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_IdCache */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_IdCache
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_IdCache
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_CachedName */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_CachedName
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_CachedName
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_Stat */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_Stat
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_Stat
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_NoMlockCacheManipulator */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_NoMlockCacheManipulator
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_NoMlockCacheManipulator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_CacheManipulator */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_CacheManipulator
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_CacheManipulator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_Pmem */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_Pmem
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_Pmem
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_PmemMappedRegion */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_PmemMappedRegion
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_PmemMappedRegion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_POSIX_SupportState */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_SupportState
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_POSIX_SupportState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
